### PR TITLE
Creating the capabilities for users to create and view reviews.

### LINKED ISSUE #17: Create Reviews for Destinations/Itineraries
As a user, I would like to create a review for a destination/itinerary, so that other users can make informed decisions based on my experience.

### LINKED ISSUE #18: Show Reviews on Destination/Itinerary
As a user, I would like to see the reviews left for a destination/itinerary, so that I can make an informed decision based on what previous user's experiences were like.

### PR DESCRIPTION
**Pull request by JustinWright6497**
Created pages for itineraries where non users can see reviews left for these itineraries and users can see reviews and also add reviews!

Close #17 
Close #18

### CODE REVIEW

**Review by Suganthi987 — DISMISSED** [review]
Review changes looks good!

**Review by Suganthi987 — APPROVED** [review]
Good Work.

**Comment by Suganthi987** [comment]
Good work!

**Comment by JustinWright6497** [comment]
Closing this PR as this PR is broken.

**Pull request closed without merging**
